apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: contact-management
spec:
  selector:
    app: routing-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort